spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/first
    username: first
    password: first
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
#kafka:
#  enabled: false